domain: haruyuki.moe
url: https://haruyuki.moe
baseurl: ""

title: "@blumewmew"
author: Haruyuki
repository: haruyuki/youtube

lang: en

plugins:
  - jekyll-seo-tag
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 12
  permalink: '/page/:num/'
  title: ' - page :num'
  sort_field: 'date'
  sort_reverse: true

color: "#13ccf9"

rrss:
  youtube: "https://www.youtube.com/@blumewmew"
  twitch: "https://www.twitch.tv/blumewmew"
  twitter: "https://x.com/blumewmew"
